### ISSUE TITLE
[upstream bug] markdown-it-attrs conflicts with markdown-it-texmath

### ISSUE THREAD

**Issue by ickc** [mb21/markdown-it-pandoc#4]
c.f. https://github.com/arve0/markdown-it-attrs/issues/115

Currently, `bracketed_spans` & `fenced_divs` has to be used with `attributes`. What's the reason behind this? Could this be lifted such that `markdown-it-attrs` can be avoided until the upstream bug is fixed, and meanwhile `markdown-it-container` & `markdown-it-bracketed-spans` can still be used?

**Comment by mb21** [comment]
`markdown-it-attrs` parses attributes behind almost any kind of element that a previous part of the parsing pipeline identified as such. That's why we rely on it to parse the attributes since [markdown-it-bracketed-spans](https://github.com/mb21/markdown-it-bracketed-spans) and [markdown-it-container](https://github.com/markdown-it/markdown-it-container) themselves don't do that...

**Comment by ickc** [comment]
I can see that markdown-it-bracketed-spans won't be quite useful without markdown-it-attrs. But seems like markdown-it-container can still be useful without that?

**Comment by mb21** [comment]
Yes, that's right... `markdown-it-container` works on its own, but the syntax is not quite the same as pandoc's...

**Comment by ickc** [comment]
Another angle would be to fix that upstream bug. It seems that’s no interest in fixing it there (or just no labor?) Do you think it is patchable within this repo, like how you did to the container for example?

**Comment by ickc** [comment]
> Yes, that's right... `markdown-it-container` works on its own, but the syntax is not quite the same as pandoc's...

#6 attempts to handle the case with `fenced_divs` without `attributes`.

**Comment by mb21** [comment]
> Another angle would be to fix that upstream bug. It seems that’s no interest in fixing it there (or just no labor?)

I think it would be best to fix upstream yes. But seems nobody has time and might also be tricky without breaking other things...

**Comment by ickc** [comment]
A safer approach would be to give it an option to change its behavior so that at least by default it won’t break someone else’ code. As this is a special case issue and using math should be optional.

**Comment by mb21** [comment]
> using math should be optional

it is, right? you can turn off `opts.katex`...

**Comment by ickc** [comment]
I mean the hypothetical fix of the upstream bug. The main problem there is it is affecting people using math but math is optional. So my point was whatever fix should be an opt in behavior as well.

**Comment by mb21** [comment]
Looks like this was fixed in markdown-it-attrs v4.1.0

(I've applied the fix in PanWriter but not yet made a release: https://github.com/mb21/panwriter/commit/012296ec8ec69f26a0c550683ddf9710c4acf9b9)
